server:
  port: 8080
spring:
  application:
    name: activiti
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver #配置JDBC Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true